### PR TITLE
Added antimagnus, calibration, grid, sustain and them.

### PR DESCRIPTION
**Pull request by penkoba**
calibration, grid: from http://tools.decodeingress.me/#/keywords.
antimagnus, sustain, them: used recently.

### CODE REVIEW

**Comment by jacktruong** [comment]
Calibration/Grid are probably not valid, it was just a script parsing error when I made the list for DI. Send a new pull with the other 3 and I'll merge.

**Comment by jacktruong** [comment]
Oh, which passcodes had those 3 keywords? Feel free to message me in private if they are still live. Thanks

**Comment by penkoba** [comment]
OK, I'll re-send another pull request with 3 keywords.

**Comment by penkoba** [comment]
Ah, sustain was from glyph.
http://glyphtionary.com/
(and I understood where calibration/grid came from :-))

I will move sustain to glyphs.txt in new PR, is that fine for you?

**Comment by jacktruong** [comment]
Yep, that's fine

**Pull request merged**
